name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    name: Build ⚙️

    env:
      CI: true

    strategy:
      matrix:
        go-version: [1.16x, 1.17x, 1.18.x, 1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go build ./...
