name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  # build:
  #   name: Build ⚙️

  #   env:
  #     CI: true

  #   strategy:
  #     matrix:
  #       go-version: [1.18.x, 1.19.x]
  #       os: [ubuntu-latest, macos-latest, windows-latest]

  #   runs-on: ${{ matrix.os }}

  #   if: "!contains(github.event.head_commit.message, '[skip ci]')"

  #   steps:
  #     - name: Checkout
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: ${{ matrix.go-version }}

  #     - name: Build
  #       run: go build ./...

  push_to_docker_hub:
    name: Push to Docker Hub 🐳

    env:
      CI: true

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    # needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to test
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/loo:latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/feature-build-cicd' }}
